# Generated by Django 4.1.7 on 2023-03-05 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomPlataforma', models.CharField(max_length=50)),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.IntegerField()),
                ('dni', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Videogames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameVideogame', models.CharField(max_length=50)),
                ('Price', models.IntegerField()),
                ('isNew', models.BooleanField()),
                ('platformProvider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videogames', to='MainApp.platform')),
                ('playersPlayed', models.ManyToManyField(to='MainApp.user')),
            ],
        ),
        migrations.AddField(
            model_name='platform',
            name='usersSuscribed',
            field=models.ManyToManyField(to='MainApp.user'),
        ),
    ]
